### ISSUE TITLE
Question: Minimum required version of gfortran

### ISSUE THREAD

**Issue by ljlamarche** [aburrell/apexpy#101]
**Describe the problem or ask the question**
What is the minimum required version of gfortran required to install the new build version of apexpy?  I've had some issues attempting to install with gfortran v4.8.5, most seem to be related to unrecognized compiler flag options.

**Desktop:**
 - OS: CentOS 7
 - Python version 3.9.2
 - Compiler: GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
 - Apexpy version/branch: 1.1.0-develop

**Comment by aburrell** [comment]
This is a good question, I've not explored many different versions of gfortran.  Which compiler flags aren't recognized?

**Comment by aburrell** [comment]
FYI I am using GNU Fortran (MacPorts gcc12 12.2.0_0+stdlib_flag) 12.2.0

**Comment by aburrell** [comment]
> just tell users to please not try to use an ancient version of gfortran.

I think this is the way to go.  Do you want to put together the PR for that, or shall I?

**Comment by ljlamarche** [comment]
I can - I had a number of clarifications I was going to request to the installation documentation for unusual cases.  Do you know if there's an easy way to figure out when those flags were added?  I was trying with google but not having much luck.  If nothing else, I'll just write it as "has been tested successfully with gfortran 7, earlier versions may not work."
