### ISSUE TITLE
[enhancement] Simplified IGRF and apexsh.dat updating

### ISSUE THREAD

**Issue by asreimer** [aburrell/apexpy#14]
There are some people (myself included) that are very interested in using apexpy to provide modified apex coordinates and vectors as part of standard incoherent scatter radar data products. Looking forward, the biggest challenge with using apexpy is maintainability in regards to updates with IGRF.

Currently, the `magfld.f` file uses hard coded IGRF coefficients. This means that when IGRF is updated, one has to modify the fortran code instead of simply updating the coefficients file. For example, the coefficient file could simply be downloaded from: https://www.ngdc.noaa.gov/IAGA/vmod/igrf12coeffs.txt and then placed in the same directory as was done in [davitpy](https://github.com/vtsuperdarn/davitpy/tree/master/tables/igrf). Current update instructions are unclear and seem to be specific to a server somewhere (Astrid Maute at NCAR?).

For example, the 2015 coefficients are hard coded here:
https://github.com/aburrell/apexpy/blob/master/src/fortranapex/magfld.f#L749-L775
https://github.com/aburrell/apexpy/blob/master/src/fortranapex/magfld.f#L1351-L1375

Additionally, the spherical harmonic fitting to the IGRF that produces the [apexsh.dat](https://github.com/aburrell/apexpy/blob/master/src/apexpy/apexsh.dat) file needs to be redone by manually compiling `makeapexsh.f90` and then the `makeapxsh` must be executed. There is also the choice of values for some of the arguments to `makeapxsh` that need to be made.

I'm envisioning 2 things:
1) Follow davitpy's example and split the IGRF table out of the fortran source code, and
2) Create some documentation that outlines how to update apexpy (how to generate the apexsh.dat file), including what is the standard set of arguments to use to regenerate the file. For example, do the same as in Emmert 2010? Use larger values for L, N, and M?

**Comment by aburrell** [comment]
I think this is a high priority issue and your envisioned work flow sounds good.  I need to go re-read Emmert 2010 to properly respond to your second point, though.

**Comment by aburrell** [comment]
This was addressed in #41 and #24.
