### ISSUE TITLE
Apex methods crash with NaNs in input coordinate arrays

### ISSUE THREAD

**Issue by ljlamarche** [aburrell/apexpy#19]
**Description**
Apex class methods throws a ValueError if input coordinate arrays include NaNs.  Here is the complete error message that I get.
```
/anaconda2/envs/python3.6/lib/python3.6/site-packages/apexpy/helpers.py:34: RuntimeWarning: invalid value encountered in greater_equal
  if np.all(np.float64(lat) >= -90) and np.all(np.float64(lat) <= 90):
/anaconda2/envs/python3.6/lib/python3.6/site-packages/apexpy/helpers.py:46: RuntimeWarning: invalid value encountered in greater
  lat[(lat > 90) & (np.isclose(lat, 90, rtol=0, atol=1e-4))] = 90
/anaconda2/envs/python3.6/lib/python3.6/site-packages/apexpy/helpers.py:47: RuntimeWarning: invalid value encountered in less
  lat[(lat < -90) & (np.isclose(lat, -90, rtol=0, atol=1e-4))] = -90
/anaconda2/envs/python3.6/lib/python3.6/site-packages/apexpy/helpers.py:48: RuntimeWarning: invalid value encountered in greater_equal
  if np.all(lat >= -90) and np.all(lat <= 90):
Traceback (most recent call last):
  File "apexpy_nan_test.py", line 20, in <module>
    alat, alon = A.geo2apex(gdlat, gdlon, 300.)
  File "/anaconda2/envs/python3.6/lib/python3.6/site-packages/apexpy/apex.py", line 240, in geo2apex
    glat = helpers.checklat(glat, name='glat')
  File "/anaconda2/envs/python3.6/lib/python3.6/site-packages/apexpy/helpers.py", line 52, in checklat
    raise ValueError(name + ' must be in [-90, 90]')
ValueError: glat must be in [-90, 90]
```
**To Reproduce**
This script will reproduce the behavior.  First, I try to convert arrays of valid geodetic latitude and longitude values, which succeeds.  Then, I replace one value in each array with `np.nan` and attempt to repeat the conversion, which now fails.

```
from apexpy import Apex
import numpy as np

# Initialize Apex
A = Apex(2019)

# Define initial geodetic lat/lon arrays
gdlat = np.array([35., 40., 45., 50., 55.])
gdlon = np.array([100., 105., 110., 115., 120.])

# Convert to apex magnetic coordinates
alat, alon = A.geo2apex(gdlat, gdlon, 300.)
print(alat, alon)

# Now replace one element in initial arrays with NaN
gdlat[3] = np.nan
gdlon[3] = np.nan
print(gdlat, gdlon)

# apexpy crashes when we try to convert these arrays
alat, alon = A.geo2apex(gdlat, gdlon, 300.)

# To try workaround, comment out the above line

# Workaround - remove nans before running conversion and reinsert them afterwards
# find indices where nans will be removed and should be inserted in new arrays
replace_nans = np.array([r-i for i,r in enumerate(np.argwhere(np.isnan(gdlat)).flatten())])
# convert
alat, alon = A.geo2apex(gdlat[np.isfinite(gdlat)], gdlon[np.isfinite(gdlon)], 300.)
# replace nans
alat = np.insert(alat, replace_nans, np.nan)
alon = np.insert(alon, replace_nans, np.nan)
print(alat, alon)
```

**Expected behavior**
The current behavior is probably actually expected (NaN locations really make no sense), but it makes it challenging to use apexpy with arbitrary data arrays.  It's fairly straight forward to remove NaNs from input arrays (`input[np.isfinite(input)]`), but then your output array has a different size than your input array.  I've been using the workaround shown at the bottom of the MWE, which seems to work, but it's a little messy.  For these kind of applications at least, it would be preferable for the NaN handling to occur within the apexpy procedure, so NaNs don't have to be filtered preemptively and the output array is the same shape as the input array.  I think it makes sense that any elements that were NaN in input arrays are NaN in output arrays. 

**Computer:**
 - OS: macOS High Sierra
 - Version: 10.13.6
 - Python version: 2.7 and 3.6
 - I've been running all code in conda environments

**Comment by aburrell** [comment]
I ran into this in aacgmv2, so I know it's solvable.  Will try and take a look next week.

**Comment by aburrell** [comment]
@ljlamarche would you like to take a look at PR #54 to ensure it fully addresses this issue?
