### ISSUE TITLE
no geocentric input possible

### ISSUE THREAD

**Issue by jarau-de** [aburrell/apexpy#22]
A little helper function is needed to convert from geocentric to geodetic coordinates. There is a conversion from geocentric latitude to geodetic but radius to altitude is missing. That is very important if one uses satellite data. The Fortran apex code already includes a method for conversion (convrt). Only a Python interface is needed.

**Comment by asreimer** [comment]
Hey @jarau-de, does [pymap3d](https://github.com/geospace-code/pymap3d) work for you? It provides many nice coordinate conversion utilities. While your request is simple, supporting a multitude of coordinate conversions isn't the intended purpose of this project. Also, [pymap3d](https://github.com/geospace-code/pymap3d) is quite excellent, so we probably don't want to reinvent the wheel here.

Maybe others have differing opinions.
