### ISSUE TITLE
No values for magnetic latitude using geo2apex in equatorial latitudes

### ISSUE THREAD

**Issue by sterfrag** [aburrell/apexpy#23]
Hello everyone,

when i use **geo2apex** to convert geodetic latitude to modified apex magnetic latitude, i do not get any values around equatorial geodetic latitudes. This does not happen when i use **geo2qd**. Why does this happen?

**Comment by klaundal** [comment]
You should get values for modified apex latitude everywhere above your reference height, if you paste a code example I can take a look.

Note that geo2apex rarely will return latitudes near the modified apex equator in most practical cases. This is because the latitude is defined by where the local field line intersects your reference height. That will only be at 0 modified apex latitude for field lines that have their apex at the reference height.

**Comment by aburrell** [comment]
This may be related to #28 and be an issue with the `abs` implementation.  Will check this out...

**Comment by aburrell** [comment]
@gregstarr if you have time, would you mind taking a look at this?

**Comment by gregstarr** [comment]
Ok sure

**Comment by gregstarr** [comment]
```
import apexpy
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

apex = apexpy.Apex(date=2019, refh=80.)
lat = np.arange(-30, 30, .1)
lon = np.arange(-90, 190, 45)
for l in lon:
    mlat, mlon = apex.geo2apex(lat, l, 120)
    plt.plot(lat, mlat, label=l)

plt.legend()
plt.xlabel("Geodetic Lat")
plt.ylabel("Apex Lat")
plt.show()
```

![mlat_test](https://user-images.githubusercontent.com/6515693/108764141-968e9380-7528-11eb-825b-7b7411d23c18.png)

I found no problem in this test

**Comment by gregstarr** [comment]
Another test:
```
import apexpy
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

apex = apexpy.Apex(date=2019, refh=80.)
lon = np.arange(360)
mlat, mlon = apex.geo2apex(0, lon, 120)
plt.plot(lon, mlat)
plt.xlabel("Longitude")
plt.ylabel("Apex lat at geodetic equator")
plt.show()
```

![mlat_test2](https://user-images.githubusercontent.com/6515693/108764421-f5540d00-7528-11eb-90b9-3039120addbe.png)

No problem here either

**Comment by gregstarr** [comment]
I was using develop in the above tests

**Comment by gregstarr** [comment]
`np.sign` only appears when converting between qd and apex

**Comment by aburrell** [comment]
Thanks @gregstarr.  I will close this as your tests seem pretty thorough.  @sterfrag please feel free to reopen this with an example if you still have a problem.
