### ISSUE TITLE
What geodetic system is used?

### ISSUE THREAD

**Issue by bharding512** [aburrell/apexpy#25]
**Describe the problem or ask the question**
First off, let me say thanks for an incredibly useful module.

I understand that apexpy converts coordinates and vectors between a geodetic coordinate system and various magnetic coordinate systems. But what geodetic system is used? To what reference ellipsoid should I interpret the geodetic latitude and altitude? WGS84?

I assume the answer is, "whatever geodetic system Emmert et al (2010) used", but I couldn't find the answer in that paper or in Richmond (1995) and Laundal and Richmond (2017). Thanks for any help you can give.

**Comment by klaundal** [comment]
It is WGS84

**Comment by aburrell** [comment]
Thanks for the questions and answers!  I'm going to keep this issue open as a reminder to put the information into the docs.
