### ISSUE TITLE
qd-to-apex conversion at the equator always returns 0 apex lat

### ISSUE THREAD

**Issue by bharding512** [aburrell/apexpy#28]
**Describe the bug**
For points above the magnetic equator and above the reference altitude, the quasi-dipole to apex conversion always returns 0 apex latitude, while the correct value is a positive latitude, if I'm understanding it correctly.

**To Reproduce**

```
import apexpy

apex = apexpy.Apex(date=2019, refh=80.)
print(apex.convert(lat=1,     lon=0, source='qd', dest='apex', height=120.))
print(apex.convert(lat=0.5,   lon=0, source='qd', dest='apex', height=120.))
print(apex.convert(lat=0.001, lon=0, source='qd', dest='apex', height=120.))
print(apex.convert(lat=0.0,   lon=0, source='qd', dest='apex', height=120.))
```

This returns:
```
(4.611886850445079, 0.0)
(4.530015978326458, 0.0)
(4.502394981072903, 0.0)
(0.0, 0.0)
```

**Expected behavior**
The last latitude should be close to 4.50, not 0.00

**Computer (please complete the following information):**
 - OS: Linux
- Python version 3.7

**Additional context**
It's probably just a simple corner case which I'd be happy to look into if you're accepting PRs. What branch do you want PRs on?

**Comment by aburrell** [comment]
Hi @bharding512 I would appreciate your work on this issue.  PRs go into the develop branch.

**Comment by gregstarr** [comment]
The problem is in this line: https://github.com/aburrell/apexpy/blob/4fe552eb90a67671816b85e534241edcb071d192/src/apexpy/apex.py#L446

if `qlat` is zero, then `np.sign(qlat)` evaluates to zero. It seems like then intention is for this to evaluate to either 1 or -1?

**Comment by aburrell** [comment]
Yes, it should evaluate to one.  Good catch!

**Comment by aburrell** [comment]
I added a unit test based on the example provided by @bharding512.
