### ISSUE TITLE
Can't compile with intel fortran compiler

### ISSUE THREAD

**Issue by gregstarr** [aburrell/apexpy#46]
**Describe the bug**
This commit https://github.com/aburrell/apexpy/commit/10358dc30a1098320896d62c613c89878c5a921f prevents compilation of the fortran sources with the intel fortran compiler `ifort`. The reason is that it uses the methods `ftell` and `fseek` which for intel fortran, you need to use the ifport library (https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/e-to-f/ftell-ftelli8.html). 

Fails with error:
```
src/fortranapex/igrf.f90(72): error #6404: This name does not have a type, and must have an explicit type.   [FTELL]
    offset = ftell(100)
```

This doesn't necessarily need fixing. I don't know anything about fortran but it seems like fortran is written with a compiler in mind?

**To Reproduce**
1. compile apexpy with the intel fortran compiler

**Computer (please complete the following information):**
 - OS: Windows 10
- Python version 3.7

**Comment by aburrell** [comment]
Fortran is written with a compiler in mind, but since you managed to find this problem, it seems worth noting.  I (hopefully) added directions to allow apexpy to work with `ifort` in #53.  Let me know if that addresses this issue from your perspective.

**Comment by gregstarr** [comment]
Yes it does. I would have been fine with not fixing this too, I just wanted to make a note of it in this issue.

**Comment by aburrell** [comment]
It was a small thing I could do at the end of the day.
