### ISSUE TITLE
ENH: adding coefficient file as an Apex input

### ISSUE THREAD

**Issue by aburrell** [aburrell/apexpy#57]
**Describe the feature**
Now that IGRF coefficients are supplied in a text file, it is possible for a user to supply their own coordinate file.  However, currently this involves going into the code and updating it manually.  It would be better for the file to be a kwarg that defaults to the provided filename.

**Comment by aburrell** [comment]
Discussed in #56 and #54.

**Comment by asreimer** [comment]
### Danger

In order to fully implement this requires rebuilding the `apexsh.dat` file

**Comment by aburrell** [comment]
Keeping this in Future for now, as this may be something we can streamline with new tools or a better understanding of current tools.  May revisit later and assign `wontfix`.

**Comment by aburrell** [comment]
Based on our current understanding of how to create/update the `apexsh.dat` file, this is a `wontfix`.  If someone finds a way to streamline this in the future, would be happy to reopen.
