### ISSUE TITLE
setup.py requires numpy, but pip doesn't automatically install numpy

### ISSUE THREAD

**Issue by asreimer** [aburrell/apexpy#6]
In the [setup.py](https://github.com/aburrell/apexpy/blob/master/setup.py#L20) file, stuff from `numpy.disutils.core` is being imported to handle compilation of the fortran libraries, which obviously requires that you have `numpy` installed.

Here's how you can reproduce the problem starting with a fresh python virtual environment (you need to have the [virtualenv](https://pypi.python.org/pypi/virtualenv) python package installed):

    [asreimer@appleton python]$ virtualenv -p python2.7 testenv2
    Running virtualenv with interpreter /usr/bin/python2.7
    New python executable in testenv2/bin/python2.7
    Also creating executable in testenv2/bin/python
    Installing Setuptools..............................................................................................................................................................................................................................done.
    Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
    [asreimer@appleton python]$ source testenv2/bin/activate
    (testenv2)[asreimer@appleton python]$ pip install a^C
    (testenv2)[asreimer@appleton python]$ python
    Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import numpy
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named numpy
    >>> 
    (testenv2)[asreimer@appleton python]$ pip install apexpy
    Downloading/unpacking apexpy
      Downloading apexpy-1.0.2.tar.gz (253kB): 253kB downloaded
      Running setup.py egg_info for package apexpy
        Traceback (most recent call last):
          File "<string>", line 16, in <module>
          File "/home/asreimer/python/testenv2/build/apexpy/setup.py", line 20, in <module>
            from numpy.distutils.core import setup, Extension
        ImportError: No module named numpy.distutils.core
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/home/asreimer/python/testenv2/build/apexpy/setup.py", line 20, in <module>

        from numpy.distutils.core import setup, Extension

    ImportError: No module named numpy.distutils.core

    ----------------------------------------
    Cleaning up...
    Command python setup.py egg_info failed with error code 1 in /home/asreimer/python/testenv2/build/apexpy
    Storing complete log in /home/asreimer/.pip/pip.log

The solution, I think, is to add:

    setup_requires=['numpy'],

[between these lines](https://github.com/aburrell/apexpy/blob/master/setup.py#L90-L91).

**Comment by aburrell** [comment]
pip doesn't support setup_requires, but I'm looking into alternative ways to ease installation for you users who don't start with numpy installed at the outset.

**Comment by asreimer** [comment]
So after some digging, the best way I found to fix this is to replicate either what `scipy` or `matplotlib` do.

`matplotlib` has some kind of delayed extension compilation class. `scipy` defines a custom `build_ext` class.

**Comment by aburrell** [comment]
I saw that.  Honestly, that was enough for me to say: Ashton, I'm going to fix this by putting a line in the readme that says to install numpy first.

I saw you forked a branch, if you want to take on this fix please feel free!

**Comment by scivision** [comment]
This issue is fixed in https://github.com/space-physics/apexpy3 by pyproject.toml, which is a generally applicable Python standard approach

**Comment by aburrell** [comment]
Just tested this after releasing v1.1.0 and it has been fixed!  Hooray!
