### ISSUE TITLE
BUG: API Reference (Autodocs) Missing on ReadTheDocs

### ISSUE THREAD

**Issue by lkilcommons** [aburrell/apexpy#72]
**Describe the bug**
Earlier versions of ApexPy had full API documentation on ReadTheDocs (https://apexpy.readthedocs.io). As of the most recent release (1.1.0), these no longer appear. This is conjuncture, but I've seen this happen when Sphinx Autodoc fails due to the package failing to import on ReadTheDocs build server.

**To Reproduce**
1. Go to https://apexpy.readthedocs.io
2. Click on https://apexpy.readthedocs.io/en/latest/reference/Apex.html
3. Note empty page

**Expected behavior**
Documentation (the docstring) for each function should be displayed

**Screenshots**
N/A

**Computer (please complete the following information):**
N/A

**Comment by aburrell** [comment]
Yes, this is a problem I wasn't able to figure out how to fix in the previous release timescale 😞. Currently I am blaming it on there being fortran code, but this wasn't a problem before.  Thanks for submitting the issue, we should tackle this before the next release.

**Comment by aburrell** [comment]
The last PR addressed this issue.  The fixed docs are on the develop branch: https://apexpy.readthedocs.io/en/develop/
