### ISSUE TITLE
BUG: Bus error: 10

### ISSUE THREAD

**Issue by ljlamarche** [aburrell/apexpy#84]
**Describe the bug**
I can install apexpy (seemingly successfully), but when I try to import the module my python session crashes with a "Bus error: 10".

```
>>> import apexpy
Bus error: 10
```

**To Reproduce**
1. Clone repo and install with `$ pip install .`
2. Start python session on CLI
3. Import apexpy module `>>> import apexpy`
4. Error will also be generated by running pytest

**Expected behavior**
The apexpy module will be imported and can be used in code.

**Computer (please complete the following information):**
 - OS: MacOS Monterey 12.1
 - Python version: 3.9.9
 - Compiler with version: gfortran 11.0.0
 - Apexpy version/branch: 1.1.0, main and develop

**Additional context**
This computer has one of the Apple M1 Pro chips, and I installed gfortran from [HPC](http://hpc.sourceforge.net/).  I'm using python from miniconda 4.10.1.

**Comment by ljlamarche** [comment]
This appears to be related to a known issue with Apple Silicon:
https://github.com/Homebrew/homebrew-core/issues/69236
https://github.com/Homebrew/homebrew-core/pull/70096
https://github.com/scipy/scipy/issues/13364
https://github.com/iains/gcc-darwin-arm64/issues/32
https://github.com/Homebrew/discussions/discussions/415
https://github.com/scipy/scipy/issues/13998

(Links are in no particular order, but it seems to be a large problem for the scipy community.)  I don't fully understand what's going on here, but it seems to be related to unaligned memory?  I've managed to install apexpy successfully (after first installing [gfortran](http://hpc.sourceforge.net/) and numpy) with the following command:

```
CFLAGS="-falign-functions=8 ${CFLAGS}" pip install --no-binary :apexpy: apexpy
```

The following links may be helpful for a more permanent solution, but I haven't looked into it in detail yet:
https://github.com/scipy/scipy/pull/14151
https://github.com/scipy/oldest-supported-numpy/pull/20

**Comment by aburrell** [comment]
This has now been added to the docs.
