### ISSUE TITLE
BUG: pip sometimes builds incompatible binary wheel in conda environments

### ISSUE THREAD

**Issue by smithara** [aburrell/apexpy#85]
**Describe the bug**
When installing in a conda environment, pip ignores the installed numpy version when making its isolated build environment which can result in an incompatible binary wheel (and apexpy fails at import). Luckily this could be avoided with:
```
pip install apexpy --no-build-isolation
```
(but I guess it could be fragile)

**To Reproduce**
Using a conda environment in Linux with numpy 1.21:
```
conda create --name test_apexpy python=3.10.2 numpy=1.21.5 libgfortran=3.0.0 gfortran=11.2.0
conda activate test_apexpy
pip install apexpy --verbose
```
During install, pip creates an isolated environment with numpy 1.22, and the subsequent build is invalid for the conda environment and apexpy will fail at import:
```
python -c "import apexpy"
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
/home/ash/mambaforge/envs/test_apexpy/lib/python3.10/site-packages/apexpy/apex.py:16: UserWarning: fortranapex module could not be imported, so apexpy probably won't work.  Make sure you have a gfortran compiler. Wheels installation assumes your compiler lives in /opt/local/bin
  warnings.warn("".join(["fortranapex module could not be imported, so ",
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ash/mambaforge/envs/test_apexpy/lib/python3.10/site-packages/apexpy/__init__.py", line 3, in <module>
    from .apex import Apex, ApexHeightError
  File "/home/ash/mambaforge/envs/test_apexpy/lib/python3.10/site-packages/apexpy/apex.py", line 20, in <module>
    raise err
  File "/home/ash/mambaforge/envs/test_apexpy/lib/python3.10/site-packages/apexpy/apex.py", line 14, in <module>
    from . import fortranapex as fa
ImportError: numpy.core.multiarray failed to import
```

 To fix the installation:
```
pip uninstall apexpy
pip cache remove apexpy
pip install apexpy --no-build-isolation
```
- See https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation

**Computer (please complete the following information):**
 - OS: Linux
 - conda environments as above

**Comment by smithara** [comment]
If I'm understanding https://numpy.org/devdocs/user/depending_on_numpy.html correctly, this can be fixed by changing the build config:
https://github.com/aburrell/apexpy/blob/ba9c59295499665a1dc833ccf4b1aa315807fcd2/pyproject.toml#L2
to:
```
requires = ["setuptools", "wheel", "Cython", "oldest-supported-numpy"] 
```

(The Numpy API/ABI is forward compatible but not backward compatible, hence the 1.22 vs 1.21 problem I found; the `oldest-supported-numpy` is a metapackage which provides a suitable low version of numpy)

I've tested that locally and seems to work but needs a closer look

**Comment by aburrell** [comment]
I will poke at this, thanks for providing so much context and a potential solution!

**Comment by smithara** [comment]
Fyi I have been looking into using [cibuildwheel](https://cibuildwheel.readthedocs.io) as a way to build the binary packages (wheels) on Github Actions. In theory it will allow a short configuration (https://github.com/smithara/apexpy/blob/change-package-build/.github/workflows/build_wheels.yml) to build these across many platforms.

That should allow most users to bypass needing the fortran compiler, and also allow systematic testing of the resulting binaries. Not sure if you can see the logs at https://github.com/smithara/apexpy/actions but I got the wheels building but then it seems that the tests (pytest) would not all pass with them. Not sure yet but it seems like they might be failing when built against the specific version of the fortran compiler used by the Github runners

**Comment by aburrell** [comment]
Ok, so because apexpy doesn't work with numpy 1.19, we can switch to 'oldest-supported-numpy' only after the oldest test version is 3.9.

**Comment by aburrell** [comment]
That won't work because (see comment way above):

> apexpy doesn't work with numpy 1.19

Since we have something that works for most cases and will work in the future, I'm going to stick with that.
