### ISSUE TITLE
Question: What is the numpy version requirement?

### ISSUE THREAD

**Issue by rafaelluizmesquita** [aburrell/apexpy#89]
**Describe the problem or ask the question**
I installed apexpy using both the github and pip install as described here: https://apexpy.readthedocs.io/en/latest/installation.html#github

While I try to import the library, it gives me a numpy ImportError: numpy.core.multiarray failed to import.

(it also throws a gfortran warning, but I have a gfortran library installed.

**Provide an example, if applicable**
Error appears on "import apexpy"

**Error log**
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

/Users/mesqur1/opt/anaconda3/lib/python3.8/site-packages/apexpy/apex.py:16: UserWarning: fortranapex module could not be imported, so apexpy probably won't work.  Make sure you have a gfortran compiler. Wheels installation assumes your compiler lives in /opt/local/bin
  warnings.warn("".join(["fortranapex module could not be imported, so ",
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-53-eefefdaf4e31> in <module>
----> 1 import apexpy
      2 

~/opt/anaconda3/lib/python3.8/site-packages/apexpy/__init__.py in <module>
      1 from __future__ import absolute_import, division, print_function
      2 
----> 3 from .apex import Apex, ApexHeightError
      4 from . import helpers
      5 

~/opt/anaconda3/lib/python3.8/site-packages/apexpy/apex.py in <module>
     18                            "a gfortran compiler. Wheels installation ",
     19                            "assumes your compiler lives in /opt/local/bin"]))
---> 20     raise err
     21 
     22 # make sure invalid warnings are always shown

~/opt/anaconda3/lib/python3.8/site-packages/apexpy/apex.py in <module>
     12 # Below try..catch required for autodoc to work on readthedocs
     13 try:
---> 14     from . import fortranapex as fa
     15 except ImportError as err:
     16     warnings.warn("".join(["fortranapex module could not be imported, so ",

ImportError: numpy.core.multiarray failed to import
**Desktop (please complete the following information):**
Edit: 
OS:
MacOS 11.6.5
Gfortran:
GNU Fortran (Homebrew GCC 11.1.0_1) 11.1.0
Apexpy: I think it's the latest one: 1.1.0

**Comment by aburrell** [comment]
Hi @rafaelluizmesquita 

Can you please provide the rest of the information needed:

OS: [e.g. iOS]
Python version [e.g. 3.6]
Compiler with version [e.g., gfortran 22]
Apexpy version/branch [e.g., 1.1.0]

It would also be helpful to know the version of numpy you're using.  There are a small range of numpy versions that don't work.

**Comment by rafaelluizmesquita** [comment]
Sorry about that. I edited in there. The numpy version is : 1.20.1

**Comment by aburrell** [comment]
Hi @rafaelluizmesquita I recently figured out that if your system is using a combination of clang and gcc it won't work.  f2py uses both the C and Fortran compilers.  That might be your problem.  You may be able to fix this by setting the `CC` environment variable to gcc and check it by using `echo $CC`.

Also, we're close to having a new release that will hopefully be easier to install. 🤞

**Comment by aburrell** [comment]
Closing due to new release and lack of activity.  Please reopen if you are still having trouble.
