### ISSUE TITLE
Question: Unable to import fortranapex

### ISSUE THREAD

**Issue by effhrong** [aburrell/apexpy#94]
**Describe the problem or ask the question**
I have successfully install the  apexpy1.0.3, but encounter some problems when import fortranapex

**Provide an example, if applicable**
1. install apexpy under subdirectory : python setup.py install
Here is the installing procedure:

PS D:\python\package\apexpy-1.0.3> python setup.py install
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "apexpy.fortranapex" sources
f2py options: []
  adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8\apexpy\fortranobject.c' to sources.
  adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8\apexpy' to include_dirs.
  adding 'build\src.win-amd64-3.8\apexpy\fortranapex-f2pywrappers.f' to sources.
  adding 'build\src.win-amd64-3.8\apexpy\fortranapex-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
writing src\apexpy.egg-info\PKG-INFO
writing dependency_links to src\apexpy.egg-info\dependency_links.txt
writing entry points to src\apexpy.egg-info\entry_points.txt
writing requirements to src\apexpy.egg-info\requires.txt
writing top-level names to src\apexpy.egg-info\top_level.txt
reading manifest file 'src\apexpy.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
writing manifest file 'src\apexpy.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
CCompilerOpt.__init__[765] : load cache from file -> D:\python\package\apexpy-1.0.3\build\temp.win-amd64-3.8\Release\ccompiler_opt_cache_ext.py
CCompilerOpt.__init__[776] : hit the file cache
get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler
Found executable D:\mingw64\bin\gfortran.exe
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
copying build\temp.win-amd64-3.8\Release\.libs\libapexsh.TOD6C5ENWQPEU6XLU3PYWUYVT5HCVAY4.gfortran-win_amd64.dll -> build\lib.win-amd64-3.8\apexpy\.libs
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\apexpy
creating build\bdist.win-amd64\egg\apexpy\.libs
copying build\lib.win-amd64-3.8\apexpy\.libs\libapexsh.TOD6C5ENWQPEU6XLU3PYWUYVT5HCVAY4.gfortran-win_amd64.dll -> build\bdist.win-amd64\egg\apexpy\.libs
copying build\lib.win-amd64-3.8\apexpy\apex.py -> build\bdist.win-amd64\egg\apexpy
copying build\lib.win-amd64-3.8\apexpy\apexsh.dat -> build\bdist.win-amd64\egg\apexpy
copying build\lib.win-amd64-3.8\apexpy\fortranapex.cp38-win_amd64.pyd -> build\bdist.win-amd64\egg\apexpy
copying build\lib.win-amd64-3.8\apexpy\helpers.py -> build\bdist.win-amd64\egg\apexpy
copying build\lib.win-amd64-3.8\apexpy\__init__.py -> build\bdist.win-amd64\egg\apexpy
copying build\lib.win-amd64-3.8\apexpy\__main__.py -> build\bdist.win-amd64\egg\apexpy
byte-compiling build\bdist.win-amd64\egg\apexpy\apex.py to apex.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\apexpy\helpers.py to helpers.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\apexpy\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\apexpy\__main__.py to __main__.cpython-38.pyc
creating stub loader for apexpy\fortranapex.cp38-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\apexpy\fortranapex.py to fortranapex.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\apexpy.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
creating 'dist\apexpy-1.0.3-py3.8-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing apexpy-1.0.3-py3.8-win-amd64.egg
removing 'd:\python\python3.8.3\lib\site-packages\apexpy-1.0.3-py3.8-win-amd64.egg' (and everything under it)
creating d:\python\python3.8.3\lib\site-packages\apexpy-1.0.3-py3.8-win-amd64.egg
Extracting apexpy-1.0.3-py3.8-win-amd64.egg to d:\python\python3.8.3\lib\site-packages
Adding apexpy 1.0.3 to easy-install.pth file
Installing apexpy-script.py script to D:\python\python3.8.3\Scripts
Installing apexpy.exe script to D:\python\python3.8.3\Scripts

Installed d:\python\python3.8.3\lib\site-packages\apexpy-1.0.3-py3.8-win-amd64.egg
Processing dependencies for apexpy==1.0.3
Searching for numpy==1.21.4
Best match: numpy 1.21.4
Adding numpy 1.21.4 to easy-install.pth file
Installing f2py-script.py script to D:\python\python3.8.3\Scripts
Installing f2py.exe script to D:\python\python3.8.3\Scripts

Using d:\python\python3.8.3\lib\site-packages
Finished processing dependencies for apexpy==1.0.3

########### EXT COMPILER OPTIMIZATION ###########
Platform      :
  Architecture: x64
  Compiler    : unix-like

CPU baseline  :
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CNL
  Generated   : none
CCompilerOpt.cache_flush[809] : write cache to path -> D:\python\package\apexpy-1.0.3\build\temp.win-amd64-3.8\Release\ccompiler_opt_cache_ext.py

2. build a draft to test, and I get this error:
 
ERROR: fortranapex module could not be imported. apexpy probably won't work
ERROR: fortranapex module could not be imported. apexpy probably won't work
Traceback (most recent call last):
  File "D:/python/PycharmProject/TITIPy-master/draft.py", line 4, in <module>
    import fortranapex
ImportError: DLL load failed while importing fortranapex: 找不到指定的模块。

**Expectations**
apexpy should work successfully

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python version 3.8.3
 - Apexpy version 1.0.3

**Comment by aburrell** [comment]
It looks like there is some sort of issue creating the library file, so that it's not recognized even though it exists in the correct place.  I've seen this happen if the compilers were installed before the Windows tools were installed.  In this case it was necessary to uninstall the compilers and windows tools, and reinstall them in the correct order (windows tools and then compilers).

**Comment by aburrell** [comment]
Closing due to new release and lack of activity.  Please reopen if you are still having trouble.
